const TARGET_FPS = 60;
const UPDATE_IN_SEC = 1 / TARGET_FPS;
const ANIMATION_INTERVAL = 150;
const ANIMATION_IN_SEC = 0.15;
const PUFFERFISH_MOVEMENT_INTERVAL = ANIMATION_IN_SEC * 1000 * 10;
const JELLYFISH_MOVEMENT_MULTIPLIER = 1 / 4;
const POISON_TICK_TIME_IN_SEC = 3;
const POISON_TICK_DAMAGE = 5;
const BOARD_WIDTH = 1920;
const BOARD_HEIGHT = 1080;

let levels = {};
