const TARGET_FPS = 30;
const FPS_INTERVAL = 1000 / TARGET_FPS;
const ANIMATION_INTERVAL = FPS_INTERVAL * 5;
const PUFFERFISH_MOVEMENT_INTERVAL = FPS_INTERVAL * 10;
const BOARD_WIDTH = 1920;
const BOARD_HEIGHT = 1080;

let levels = {};

console.log(ANIMATION_INTERVAL);
