const TARGET_FPS = 30;
const UPDATE_IN_SEC = 1 / TARGET_FPS;
const ANIMATION_INTERVAL = UPDATE_IN_SEC * 1000 * 5;
const PUFFERFISH_MOVEMENT_INTERVAL = UPDATE_IN_SEC * 1000 * 10;
const BOARD_WIDTH = 1920;
const BOARD_HEIGHT = 1080;

let levels = {};
